// Renders the build-time release status. version.json is generated by build.sh
// and is never committed — the version number is computed, not stored.
(function () {
  "use strict";

  var FIELDS = ["version", "tag", "commit", "branch"];
  var KNOWN_ENVS = ["dev", "uat", "production"];

  function setText(id, value) {
    var el = document.getElementById(id);
    if (el) el.textContent = value;
  }

  function render(info) {
    FIELDS.forEach(function (field) {
      setText(field, info[field] || "unknown");
    });

    var env = (info.environment || "unknown").toLowerCase();
    var badge = document.getElementById("env");
    if (badge) {
      badge.textContent = env;
      badge.className =
        "badge badge--" + (KNOWN_ENVS.indexOf(env) === -1 ? "unknown" : env);
    }

    setText("built", info.built_at ? "built at " + info.built_at : "built at unknown");

    var link = document.getElementById("repo-link");
    if (link && info.repository) {
      var base = "https://github.com/" + info.repository;
      link.href = info.commit && info.commit !== "unknown" ? base + "/commit/" + info.commit : base;
      link.textContent = info.repository;
    }

    document.title = "Release status — " + (info.version || "unknown");
  }

  fetch("./version.json", { cache: "no-store" })
    .then(function (res) {
      if (!res.ok) throw new Error("HTTP " + res.status);
      return res.json();
    })
    .then(render)
    .catch(function (err) {
      console.error("Could not load version.json:", err);
      render({ environment: "unknown" });
    });
})();
